### ISSUE TITLE
列表以外的邮箱是否可以使用这个包？

### ISSUE THREAD

**Issue by cwu2011** [ZYunH/zmail#18]
我想用我们学校的邮箱账户（mail.fafu.edu.cn）发送邮件。发送的时候出现以下错误。
学校的邮箱使用的是一个叫盈世Coremail的邮件系统。
请问zmail是否支持这个邮件系统？
Traceback (most recent call last):
  File "E:/git_repositoty/autoMailGenerate/src/smtpMail.py", line 12, in <module>
    server.send_mail('49108565@qq.com', mail)
  File "D:\Python36\lib\site-packages\zmail\server.py", line 54, in send_mail
    server.send_ssl(recipients, message, timeout)
  File "D:\Python36\lib\site-packages\zmail\server.py", line 169, in send_ssl
    with smtplib.SMTP_SSL(self.host, self.port, __local__, timeout=timeout) as server:
  File "D:\Python36\lib\smtplib.py", line 1030, in __init__
    source_address)
  File "D:\Python36\lib\smtplib.py", line 251, in __init__
    (code, msg) = self.connect(host, port)
  File "D:\Python36\lib\smtplib.py", line 336, in connect
    self.sock = self._get_socket(host, port, self.timeout)
  File "D:\Python36\lib\smtplib.py", line 1036, in _get_socket
    self.source_address)
  File "D:\Python36\lib\socket.py", line 724, in create_connection
    raise err
  File "D:\Python36\lib\socket.py", line 713, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。

**Comment by ZYunH** [comment]
学校邮箱可以支持  请切换到邮箱设置看看smtp 或者pop3功能是否打开    或者是否有其他的服务地址




| |
张云浩
邮箱：workvl@163.com
|

签名由 网易邮箱大师 定制

在2018年03月21日 23:04，c. wu 写道：

我想用我们学校的邮箱账户（mail.fafu.edu.cn）发送邮件。发送的时候出现以下错误。
学校的邮箱使用的是一个叫盈世Coremail的邮件系统。
请问zmail是否支持这个邮件系统？
Traceback (most recent call last):
File "E:/git_repositoty/autoMailGenerate/src/smtpMail.py", line 12, in
server.send_mail('49108565@qq.com', mail)
File "D:\Python36\lib\site-packages\zmail\server.py", line 54, in send_mail
server.send_ssl(recipients, message, timeout)
File "D:\Python36\lib\site-packages\zmail\server.py", line 169, in send_ssl
with smtplib.SMTP_SSL(self.host, self.port, local, timeout=timeout) as server:
File "D:\Python36\lib\smtplib.py", line 1030, in init
source_address)
File "D:\Python36\lib\smtplib.py", line 251, in init
(code, msg) = self.connect(host, port)
File "D:\Python36\lib\smtplib.py", line 336, in connect
self.sock = self._get_socket(host, port, self.timeout)
File "D:\Python36\lib\smtplib.py", line 1036, in _get_socket
self.source_address)
File "D:\Python36\lib\socket.py", line 724, in create_connection
raise err
File "D:\Python36\lib\socket.py", line 713, in create_connection
sock.connect(sa)
TimeoutError: [WinError 10060] 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。
