### ISSUE TITLE
AttributeError: module 'smtplib' has no attribute 'SMTP_SSL'

### ISSUE THREAD

**Issue by Magnosaurus** [ZYunH/zmail#20]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/python3.6/lib/python3.6/site-packages/zmail/server.py", line 54, in send_mail
    server.send_ssl(recipients, message, timeout)
  File "/usr/local/python3.6/lib/python3.6/site-packages/zmail/server.py", line 169, in send_ssl
    with smtplib.SMTP_SSL(self.host, self.port, __local__, timeout=timeout) as server:
AttributeError: module 'smtplib' has no attribute 'SMTP_SSL'

**Comment by wilsonLwx** [comment]
Did you solve this proble? I have meeting the same proble!

**Comment by Deepak-7564** [comment]
I got the same issue in windows. But it works fine on linux OS.
