### ISSUE TITLE
使用get_mails函数报错

### ISSUE THREAD

**Issue by mysaber** [ZYunH/zmail#22]
Traceback (most recent call last):
  File "/Users/chillser/PycharmProjects/weld_mail/apps/mail/models.py", line 10, in <module>
    mails = server.get_mails(after='2018-5-10')
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/server.py", line 83, in get_mails
    info = self.get_info()
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/server.py", line 115, in get_info
    result = server.get_info()
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/server.py", line 245, in get_info
    header = self.get_header(count)
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/server.py", line 272, in get_header
    return self.pop3.top(which, 0)[1]
  File "/Users/chillser/.pyenv/versions/3.5.1/lib/python3.5/poplib.py", line 337, in top
    return self._longcmd('TOP %s %s' % (which, howmuch))
  File "/Users/chillser/.pyenv/versions/3.5.1/lib/python3.5/poplib.py", line 183, in _longcmd
    return self._getlongresp()
  File "/Users/chillser/.pyenv/versions/3.5.1/lib/python3.5/poplib.py", line 159, in _getlongresp
    resp = self._getresp()
  File "/Users/chillser/.pyenv/versions/3.5.1/lib/python3.5/poplib.py", line 152, in _getresp
    raise error_proto(resp)
poplib.error_proto: b"-ERR Can't get the letter xtbBLQwAABrqlERZ8pmJc6[301], try again later"

**Comment by ZYunH** [comment]
看起来是pop协议无法拉取邮箱的一些邮件，能稳定复现吗？

**Comment by mysaber** [comment]
可以稳定重现，我使用的是126邮箱测试的

**Comment by ZYunH** [comment]
这个是因为邮箱内的部分邮件信头信息被破坏而导致的，可以到邮箱客户端内把这个邮件删除或者移动到别的文件夹就可以解决这个问题。根据已有信息猜测这是第301封邮件。另：get_mails出现一些问题，将会在近期修复

**Comment by ZYunH** [comment]
it works now.可以查看最新版本已更新.如果还有问题请在此issue下继续留言~
