### ISSUE TITLE
编码问题

### ISSUE THREAD

**Issue by mysaber** [ZYunH/zmail#23]
[CRITICAL] Can not decode basic "subject",Use Unknownsubject instead, raw:b'\xd4\xda\xb7\xe7\xd0\xd0\xb5\xc4Email\xd1\xe9\xd6\xa4'
[CRITICAL] Can not decode basic "from",Use Unknownfrom instead, raw:b'"\xb7\xe7\xd0\xd0\xcd\xf8\xc2\xe7\xb5\xe7\xd3\xb0" <support@funshion.net>'
[CRITICAL] Can not decode basic "to",Use Unknownto instead, raw:b'"\xc1\xd6\xc4\xb3\xc4\xb3"'
Traceback (most recent call last):
  File "/Users/chillser/PycharmProjects/weld_mail/apps/mail/models.py", line 16, in <module>
    print(server.get_mail(x))
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/server.py", line 79, in get_mail
    return mail_decode(mail, which)
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/message.py", line 71, in mail_decode
    return MailDecode(mail_as_bytes, which).result
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/message.py", line 318, in __init__
    _content, _content_html = self.one_part_decode()
  File "/Users/chillser/.virtualenvs/weld_mail/lib/python3.5/site-packages/zmail/message.py", line 420, in one_part_decode
    _content.append(i.decode(self.charset))
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xc0 in position 9: invalid start byte

**Comment by ZYunH** [comment]
这是因为解析邮件 头信息时没有找到charset或者没有正确解析 默认使用utf-8解析出现错误 此时正确的编码应该是GBK 一些在邮件提供商内部传送的邮件会以自己定义的非常规方式提供charset可能导致此错误 可以提供一下邮件头信息吗？ 就是包含content-type subject 这一类的头部信息再来解析一下什么问题
