### ISSUE TITLE
发送失败，之前还可以的

### ISSUE THREAD

**Issue by githhhh** [ZYunH/zmail#31]
Traceback (most recent call last):
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/smtplib.py", line 353, in send
    self.sock.sendall(s)
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 891, in sendall
    v = self.send(data[count:])
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 861, in send
    return self._sslobj.write(data)
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/ssl.py", line 586, in write
    return self._sslobj.write(data)
socket.timeout: The write operation timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "SendMail.py", line 48, in <module>
    server.send_mail('xxx', mail_content)
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail/server.py", line 54, in send_mail
    server.send_ssl(recipients, message, timeout)
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail/server.py", line 175, in send_ssl
    server.sendmail(self.user, recipient, message.as_string())
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/smtplib.py", line 877, in sendmail
    (code, resp) = self.data(msg)
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/smtplib.py", line 567, in data
    self.send(q)
  File "/Users/bin/.pyenv/versions/3.5.2/lib/python3.5/smtplib.py", line 356, in send
    raise SMTPServerDisconnected('Server not connected')
smtplib.SMTPServerDisconnected: Server not connected

**Comment by ZYunH** [comment]
为了更好的debug，如果可以的提供一下以下信息
1.请用pip3 list 看一下zmail版本
2.使用的邮箱服务商（例如163、qq等）

**Comment by ZYunH** [comment]
尝试以下reinstall，现在最新版本为0.1.4:
1. pip3 uninstall zmail
2. pip3 install zmail

**Comment by githhhh** [comment]
xx@MacBook-Pro ~/Desktop> pip uninstall zmail                                                     1
Uninstalling zmail-0.1.4:
  Would remove:
    /Users/xx/.pyenv/versions/3.5.2/lib/python3.5/site-packages/test/*
    /Users/xx/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail-0.1.4.dist-info/*
    /Users/xx/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail/*
Proceed (y/n)? y
  Successfully uninstalled zmail-0.1.4
xx@MacBook-Pro ~/Desktop> pip install zmail
Collecting zmail
  Using cached https://files.pythonhosted.org/packages/5c/e5/b44a9fa57219e3704ae5eb33e6598443e71f8f2bc1c7503d8abd797f0545/zmail-0.1.4-py3-none-any.whl
Installing collected packages: zmail
Successfully installed zmail-0.1.4
xx@MacBook-Pro ~/Desktop> python SendMail.py
Traceback (most recent call last):
  File "SendMail.py", line 1, in <module>
    import zmail
  File "/Users/xx/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail/__init__.py", line 7, in <module>
    from .api import *
  File "/Users/xx/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail/api.py", line 8, in <module>
    from .server import MailServer
  File "/Users/xx/.pyenv/versions/3.5.2/lib/python3.5/site-packages/zmail/server.py", line 52
    message['from'] = f'{self.user.split("@")[0]}<{self.user}>'
                                                              ^
SyntaxError: invalid syntax

**Comment by ZYunH** [comment]
这个是python3.5 3.6的语法兼容问题 ， 现在已经修复 ，重新安装一下即可

**Comment by githhhh** [comment]
多谢，解决了。但是 3.6.0 还是有问题
Traceback (most recent call last):
  File "SendMail.py", line 1, in <module>
    import zmail
ModuleNotFoundError: No module named 'zmail'

然后我切到3.5.2 是没问题的

**Comment by ZYunH** [comment]
切换到3.6.0有这个问题是因为你没在py3.6里面安装zmail，安装完就好啦~
