### ISSUE TITLE
发送很多邮件都只是显示成功，要不就是发不出去程序停止

### ISSUE THREAD

**Issue by linkangren** [ZYunH/zmail#90]
只是返回true，要不就是超时发不出去，有什么好方法解决吗

**Comment by linkangren** [comment]
Exception in thread Thread-2:
Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "D:/python/Email/Email.py", line 128, in email_http
    a = server.send_mail(email2_name, mail)
  File "C:\Users\admin\venv\lib\site-packages\zmail\server.py", line 116, in send_mail
    server.send(recipients, _mail,
  File "C:\Users\admin\venv\lib\site-packages\zmail\server.py", line 280, in send
    self.server.sendmail(self.username, recipients, mail.get_mime_as_string())
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 876, in sendmail
    (code, resp) = self.rcpt(each, rcpt_options)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 546, in rcpt
    self.putcmd("rcpt", "TO:%s%s" % (quoteaddr(recip), optionlist))
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 371, in putcmd
    self.send(str)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python38\lib\smtplib.py", line 355, in send
    s = s.encode(self.command_encoding)
UnicodeEncodeError: 'ascii' codec can't encode character '\u2014' in position 20: ordinal not in range(128)错误信息

**Comment by ZYunH** [comment]
看上去是因为解析错误，可能邮件中携带了非法的信息。也有可能是py3.8基础库的问题，因为错误发生在Python38\lib\smtplib.py  line 355
